name: Test
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - uses: ./
      with:
        version: latest
        abq-token: ${{ secrets.ABQ_API_KEY }}
    - run: |
        echo "$PATH"
        abq --version
